### ISSUE TITLE
Replies via micropub not syndicating properly

### ISSUE THREAD

**Issue by miklb** [indieweb/wordpress-micropub#167]
I have tested desktop replies using the same url as micropub and bridgy syndicates as a reply from desktop but not via micropub. Testing both Quill in desktop browser and Indigenous on iOS with same results.

Where does the syndicate-to fire in relation to the note being built?

**Comment by miklb** [comment]
This may be an issue with post kinds plugin and shouldn't be a blocker IMO for a 2.0 release.

**Comment by dshanske** [comment]
https://github.com/indieweb/wordpress-micropub/commit/752897ed70b1b4e5e60dac9ef227a3ab9a9e98d9
