### ISSUE TITLE
Plugin protects access to all Wordpress wp-json API endpoints

### ISSUE THREAD

**Issue by lostfocus** [indieweb/wordpress-micropub#172]
When the plugin is active all wp-json endpoints are returning a 401 error if called without a token, even the public ones  which isn't quite the expected and/or wanted behaviour.

(Example: `/wp-json/wp/v2/posts` which should be accessible without a token.)

**Comment by lostfocus** [comment]
I'm pretty sure that's somewhere in `determine_current_user` https://github.com/indieweb/wordpress-micropub/blob/2.0.0/includes/class-micropub-authorize.php#L158 - calls to a public API endpoint usually do not have an auth header or a token.

**Comment by dshanske** [comment]
Oddly, I'm seeing this now after the authorize piece moved in 2.0.1 to fix a different problem.When it shouldn't be loading.

**Comment by lostfocus** [comment]
That could be something with the order of hooks and filters.

**Comment by dshanske** [comment]
I'm working on it.

**Comment by snarfed** [comment]
ugh, this bit me too. thanks @lostfocus!

@dshanske i'm definitely looking forward to the fix. the current status is pretty painful, since i can only have webmentions or micropub work, not both, so this seems pretty urgent. do you have a recommended workaround? or just expediting your fix?

**Comment by dshanske** [comment]
Resolved in Version 2.0.2
