### ISSUE TITLE
undelete scope insufficient

### ISSUE THREAD

**Issue by grantcodes** [indieweb/wordpress-micropub#184]
Heyo!

Just testing out a micropub client with a test WordPress site and when trying to undelete posts I am getting an insufficient scope message even though I have the `create`, `delete`  & `update` scopes.

I don't think there is anything that explicitly says which scope should be required for undelete requests, but I thought `create` should be enough.

**Comment by dshanske** [comment]
Do the other scopes work for you? Just to narrow it down? We do accept delete or undelete as the scope.

**Comment by grantcodes** [comment]
Hmm well I was able to create the post and delete it, but not undelete. But I've not tested without the scopes

**Comment by dshanske** [comment]
I have not tested undelete in ages. May be time to do some additional testing. We have a unit test for it, but I can't remember the last time I did a user test

**Comment by dshanske** [comment]
I think this should be delete. There is no undelete scope

**Comment by dshanske** [comment]
Resolved via #204
