### ISSUE TITLE
Feature: support querying last uploaded in Micropub media endpoint

### ISSUE THREAD

**Issue by dougbeal** [indieweb/wordpress-micropub#190]
Feature: support querying last uploaded in Micropub media endpoint
https://indieweb.org/micropub_media_endpoint#Query_the_last_thing_uploaded

**Comment by dougbeal** [comment]
should work with Quill – https://github.com/aaronpk/Quill/issues/98

**Comment by dshanske** [comment]
Added in version 2.0.9

**Comment by dougbeal** [comment]
Verified.
curl -X GET -H ‘Authorization: Bearer &lt;from Quill&gt;’ -H ‘Content-type: application/json’ https://dougbeal.com/wp-json/micropub/1.0/media?q=last
{"url":"https://dougbeal.com/wp-content/uploads/2019/03/igbSx9Vm.jpg"}
