### ISSUE TITLE
Video files sent to media endpoint blocked by WordPress

### ISSUE THREAD

**Issue by jjeaton** [indieweb/wordpress-micropub#199]
A follow on issue to #173, we are seeing video/mp4 files blocked as of WP 5.0.1. I believe I was able to upload the same video file directly to the media library.

I’ll do some more testing when I can to confirm this.

Tests:

- [x] Can video/mp4 be uploaded to media library?
- [x] Can video/mp4 be uploaded via core REST API endpoint?

**Comment by dshanske** [comment]
Waiting on pushing a new version to see if there is a fix for this

**Comment by jjeaton** [comment]
@dshanske I've been able to upload an mp4 to the media library, through the core /wp/v2/media endpoint AND through the /micropub/1.0/media endpoint. This may be a false alarm, or just something about how OwnYourGram is sending the videos. I think we can close this out, and I'll re-open if I find anything else.
