### ISSUE TITLE
Error when uploading an image via Indigenous

### ISSUE THREAD

**Issue by ngm** [indieweb/wordpress-micropub#203]
I get an error when using 'Upload' from Indigenous for Android.

> Media posting failed.  Status code: 500; message: {"error":"invalid_request","error_description":[0]}

Creating a note with an image included inside does work, it seems to be just when uploading to the media endpoint.

**Comment by ngm** [comment]
I will try and test from a different client to see what happens.

**Comment by dshanske** [comment]
I have tracked this to something different Indigenous does. Accounting for it in code

**Comment by dshanske** [comment]
Resolved via #204
