### ISSUE TITLE
Return URL to post in JSON

### ISSUE THREAD

**Issue by RosemaryOrchard** [indieweb/wordpress-micropub#206]
I would like to request a URL to the created or modified post in the JSON, this would allow users (such as myself) to open it when posting via Shortcuts which does not have access to the header data.

**Comment by dshanske** [comment]
In what format?

**Comment by Zegnat** [comment]
[Rose](https://chat.indieweb.org/dev/2019-09-29/1569788127450700):
> same as Media Endpoint? Sorry, I’m not logged into GitHub here.

**Comment by sknebel** [comment]
which would be `{"url":"<url>"}` (the media endpoint response also contains an "id", I do not know if that's useful information for a post in wordpress too)

**Comment by dshanske** [comment]
Posts have ids in WordPress

**Comment by dshanske** [comment]
@RosemaryOrchard Since you pushed this, are you satisfied and can close the issue?

**Comment by RosemaryOrchard** [comment]
It is indeed perfect!
