### ISSUE TITLE
Switch to dynamic rendering

### ISSUE THREAD

**Issue by dshanske** [indieweb/wordpress-micropub#211]
Regardless of the considerations in how mf2 plugins should relate, this plugin should stop encoding microformats into the post content and add these on the fly. 

@snarfed, @pfefferle I need your input on this. 

My proposal is to mark all existing posts made by Micropub on upgrade by adding a meta key. That will have them processed the current way.

For new posts, post_content will only contain e-content, and the other properties will be added on the fly. 

This will be disabled if Post Kinds handles rendering. 

You already couldn't effectively use the editor for editing Micropub posts without manually editing the HTML. With Post Kinds you could, and with Gutenberg you still cannot.

So, this sets up for more flexibility on what we might do in future. I just want help ensuring nothing gets messed up.

**Comment by snarfed** [comment]
🎉 🚢

**Comment by dshanske** [comment]
> 🎉 🚢

A few minor things before the version release to do. Then wait for the fireworks.
