### ISSUE TITLE
Authorization: header is getting stripped when make a request through micropub endpoint

### ISSUE THREAD

**Issue by amandarush** [indieweb/wordpress-micropub#219]
The following is from a very long conversation I had with my host, WPEngine, upon trying to publish to my endpoint from my machine.

Today we took a look at the 403's that we're receiving from the following endpoint : /wp-json/micropub/1.0/endpoint and here's an example of a 403 request in our NGINX logs from your publishing 19/Feb/2020:22:54:46 +0000|v1|71.58.158.219|www.arush.io|403|146|-|-|0.000|POST /wp-json/micropub/1.0/endpoint HTTP/1.0|0|0|- .
We went ahead and whitelisted your IP just to double check that wasnt causing the issue. After doing so we were still receiving 403's on each request and afterwards I took a look at the plugins documentation here: https://github.com/indieweb/wordpress-micropub
It looks like the Authorization: header is getting stripped whenever you make a request through this specific endpoint. As per the plugins instructions, we've attempted to add the .htaccess defines that were listed to no avail. The WP-Config define also does not work and will cause a 500 error on the site due to database caching. If there is a custom define that we need to add into the wp-config.php file to serve the Authorization: headers then the plugin dev should have that info; I see in their documentation they offer solutions on how to pass the token through a custom header. On our end, we also tried to pass this request directly to Apache, but it still gets served a 403 immediately in NGINX.
We'd love to hear back from the Developer about any potential solutions on why we're seeing this particular endpoint fail. We've verified that the token is valid here, so that shouldn't be our issue. I do look forward to hearing back from you soon!
WP Engine Nick V. | Support Resources:

I'm going to add this issue to the ticket in case N wants to comment, and can add the information sent as the header as well if necessary and revoke the token afterwords if that's helpful.

**Comment by amandarush** [comment]
I should add that publishing from Quill, Teacup, and Indieweb Book Club all work, as does Own Your Swarm. All are hosted with their respective developers.

**Comment by aaronpk** [comment]
I'm confused, are they saying they can't figure out why their web server is stripping the Authorization header?

**Comment by amandarush** [comment]
@aaronpk that is exactrly what they are telling me. They don't know why it's being blocked, and it's completely unexplainable to me because I can use other apps just fine. I even have an IfTTT web hook recipe that I was experimenting with, using this exact same method but a different token obviously, and it works.

**Comment by amandarush** [comment]
Just as a further test, I attempted to pass a token from my local environment to the server which I personally know is valid and works. No dice. Will see if Icro breaks as well. Just adding this info to the issue in case WPE is actually looking at it and the original ticket gets passed off and someone suggests something like lack of URL since things like Quill ETC. work. Hopefully all of this helps another WPE user.

**Comment by dshanske** [comment]
Closing this due Indieauth issues to be handled by the Indieauth plugin.
