### ISSUE TITLE
403 forbidden - Unauthorized

### ISSUE THREAD

**Issue by ivanvetoshkin** [indieweb/wordpress-micropub#228]
Hi! I've got the same problem with Quill as described in #150 but I don't have any `www`s forced on my website. Here's my debug.log:

```
[18-Jul-2020 17:57:54 UTC] Micropub Error: 403 forbidden - Unauthorized
[18-Jul-2020 17:57:54 UTC] PHP Warning:  Invalid argument supplied for foreach() in /var/www/common/wp-includes/rest-api/class-wp-rest-server.php on line 1269
```

I've checked the HOME_URL, the URL I've put into Quill when authenticating and, just in case, my WP user's URL. They're all with `https://`. I'm lost. What could be the problem?

**Comment by dshanske** [comment]
Are you using the IndieAuth plugin or this plugin alone?

**Comment by ivanvetoshkin** [comment]
This plugin alone.

**Comment by dshanske** [comment]
The plugin alone requires configuring for an external IndieAuth endpoint. Have you done so?

**Comment by ivanvetoshkin** [comment]
I set it up as described [here at IndieWeb Wiki](https://indieweb.org/IndieAuth#Set_up_using_IndieAuth.com) and successfully logged in there, so, I guess, it works properly. Shall I do anything else?

**Comment by dshanske** [comment]
Can you add the IndieAuth plugin and try with the local endpoint? IndieAuth.com is being slowly shut down.

**Comment by ivanvetoshkin** [comment]
Yeah, I installed the IA plugin, and everything worked. Thanks!
