### ISSUE TITLE
Support Featured Image (and other common WordPress functionality)

### ISSUE THREAD

**Issue by chrisaldrich** [indieweb/wordpress-micropub#24]
I'm not sure if it's something that would fit in here or quite how -- perhaps a setting toggle?, but for clients that push photos (OwnYourGram.com, https://ownyourcheckin.wirres.net/, Quill, et al), it would be nice on WordPress (especially for many modern themes) to have the (primary) photo from the client post as a "Featured Image" rather than in the main body of the post.

Other potential settings-based functionalities I can imagine being useful (based on experience with Twitter clients) include 
- being able to set future posting times
- saving posts as draft, private, pending, etc. rather than automatically publishing
- allowing one to set Post Format (or if using the IndieWeb Post Kinds plugin: Post Kind)
  Naturally supporting some of this would also depend on the posting client having support for these options as well.

**Comment by snarfed** [comment]
thanks for the detailed feature requests @chrisaldrich! much appreciated.

i don't actually use this plugin myself, so i don't actively develop it much. i've merged a handful of @dshanske's PRs, though, and he's expressed interested in doing more. fingers crossed!

**Comment by chrisaldrich** [comment]
<a href="https://github.com/snarfed/wordpress-micropub/issues/24#issuecomment-223158982" class="u-in-reply-to"></a>@snarfed, no worries; I know you're certainly doing better/more important work in other quarters than this.  Besides, I don't just hold my breath waiting for things like this, sometimes I turn blue and fall off my chair... :)  maybe I'll finish dusting off some of my rusty coding skills and get around to this myself after a few other itches. 

Some of these types of niceties are going to be more "necessary" as IndieWeb Generation 2 starts onboarding heavily...

**Comment by dshanske** [comment]
1. Setting a future posting time is technically supported already. The plugin supports setting a published date. Allowing one to be set in the future is a client issue.
1. Discussed the draft option today, and no one currently supports it, but this plugin could be the trendsetter. The tentative proposal is a property... p-x-status, indicating an experimental status. The plugin already has a server side setting to set everything to DRAFT mode for debugging purposes.
1. Currently Post Kinds tries to use implied types, as opposed to explicit ones, if it gets a micropub input, so this is covered...but supporting the built-in Post Formats is probably worth a look.

**Comment by miklb** [comment]
I'm exploring this myself, specifically wanting attached image set as a featured image so I can have better control over responsive images in my theme. I'm not sure the micropub plugin is the best place to do that though. There seems to be some [plugins](https://wordpress.org/plugins/easy-add-thumbnail/) that can do that, or a theme function can filter `the_content` to do so. This would allow the theme to use custom thumbnail sizes. @chrisaldrich I'll be sure to share the function I cook up if you are interested.

**Comment by dshanske** [comment]
Setting as a featured image should be in the Plugin. Displaying it is a theme issue.

**Comment by dshanske** [comment]
We have Post Status now. We don't have featured, but featured is not necessarily, as pointed out to me, an image, so we have the issue that WordPress doesn't support featured video or audio.

https://indieweb.org/mp-type 

For setting the post kind, since Micropub doesn't require Post Kinds, it seems this would be something that Post Kinds would have to support, and could do so using filters. 

Post Kinds already hooks onto the after_micropub action to set a Post Kind for the post based on Post Type Discovery. Thoughts?

**Comment by dshanske** [comment]
@chrisaldrich Can we close this?

**Comment by dshanske** [comment]
Closed due no response from @chrisaldrich . Reopen if needed, or file more specific issue.
