### ISSUE TITLE
not adding in-reply-to link to content

### ISSUE THREAD

**Issue by snarfed** [indieweb/wordpress-micropub#66]
it comes through in the request, and gets stored in post meta, but doesn't get added to the post content.

(thanks to @anomalily for reporting at IWS 2017!)

**Comment by snarfed** [comment]
deprioritizing this. I'm hoping the next release will switch to rendering mf2 properties at page load time instead, which should address this too.

**Comment by dshanske** [comment]
I believe I fixed this with @anomalily at IWS 2018.
