### ISSUE TITLE
Quill's itinerary posting ui fails silently when used with this endpoint

### ISSUE THREAD

**Issue by dshanske** [indieweb/wordpress-micropub#77]
I was trying this just for interest and it failed. While I would be interested in getting it working, I am more concerned about the fact it says it posted successfully but didn't.

Will investigate at some point.

**Comment by snarfed** [comment]
what's an itinerary? what exactly is quill posting? mind adding details?

**Comment by dshanske** [comment]
I intend to when time permits.

**Comment by snarfed** [comment]
hey @dshanske any luck reproducing or debugging this?

**Comment by snarfed** [comment]
friendly ping! is there a bug or feature request here?

**Comment by dshanske** [comment]
There will be. Been distracted with other things. My intention is to track this down myself, if you want to assign it to me.

**Comment by dshanske** [comment]
2017/12/20 23:29:02 [error] 875#875: *11681 FastCGI sent in stderr: "PHP message: Micropub Data: a:1:{s:8:"micropub";s:8:"endpoint";} a:2:{s:4:"type";a:1:{i:0;s:7:"h-entry";}s:10:"properties";a:1:{s:9:"itinerary";a:1:{i:0;a:2:{s:4:"type";a:1:{i:0;s:5:"h-leg";}s:10:"properties";a:7:{s:12:"transit-type";a:1:{i:0;s:3:"air";}s:8:"operator";a:1:{i:0;s:10:"Aer Lingus";}s:6:"number";a:1:{i:0;s:3:"104";}s:6:"origin";a:1:{i:0;s:3:"JFK";}s:11:"destination";a:1:{i:0;s:3:"DUB";}s:9:"departure";a:1:{i:0;s:22:"2017-12-21T17:00-05:00";}s:7:"arrival";a:1:{i:0;s:21:"2017-12-22T05:0000:00";}}}}}}
PHP message: PHP Notice:  Undefined index: action in /wordpress-micropub/micropub.php on line 230
PHP message: PHP Notice:  Undefined index: url in /wordpress-micropub/micropub.php on line 231
PHP message: PHP Notice:  Undefined index: syndicate-to in /wp-content/plugins/wordpress-micropub/micropub.php on line 235
PHP message: PHP Warning:  array_diff(): Argument #1 is not an array in /wordpress-micropub/micropub.php on line 236
PHP message: PHP Notice:  Undefined index: slug in /wordpress-micropub/micropub.php on line 505
PHP message: PHP Notice:  Undefined index: name in /wordpress-micropub/micropub.php on line 505
PHP message: PHP Notice:  Undefined index: summary in /wordpress-micropub/micropub.php on line 505
PHP message: PHP Notice:  Undefined index: content in /wordpress-micropub/micropub.php on line 553
PHP message: PHP Notice:  Undefined index: summary in /wordpress-micropub/micropub.php on line 559
PHP message: PHP Notice:  Undefined index: replace in /wordpress-micropub/micropub.php on line 571
PHP message: PHP Notice:  Undefined index: checkin in

**Comment by snarfed** [comment]
hey @dshanske do you want to try to fix this before i cut the 1.3 release?

**Comment by dshanske** [comment]
No, I am going to punt it for now.

**Comment by dshanske** [comment]
I've been looking at this. WordPress returns the error that there is no summary, content, or title, but Quill says a location header has been found.

**Comment by dshanske** [comment]
@aaronpk This is related to: https://github.com/aaronpk/Quill/issues/93 , however, I'm curious why Quill insists a location header has been found, as it isn't returning one that I can see on my side.

**Comment by dshanske** [comment]
This now works in stable, if with no summary and thus unreadable.
